// Fila de reposição: quando um cartão do baralho principal é excluído,
// o próximo daqui entra no lugar, mantendo sempre 200 palavras ativas.
const BACKLOG = [
  { es: "la cinta", pt: "fita", ex: "Pega la caja con cinta.\nCola a caixa com fita.", note: "cinto = el cinturón" },
  { es: "el cinturón", pt: "cinto", ex: "Abróchate el cinturón.\nAperta o cinto." },
  { es: "la carpeta", pt: "pasta (de papéis)", ex: "Los documentos están en la carpeta.\nOs documentos estão na pasta.", note: "carpete = la moqueta" },
  { es: "el cartel", pt: "cartaz", ex: "Vi el cartel de la película.\nVi o cartaz do filme." },
  { es: "la cola", pt: "fila / rabo", ex: "Hay mucha cola en el banco.\nTem muita fila no banco.", note: "cola (de colar) = el pegamento" },
  { es: "el pegamento", pt: "cola", ex: "Necesito pegamento para el papel.\nPreciso de cola para o papel." },
  { es: "el despacho", pt: "gabinete / sala de trabalho", ex: "El jefe está en su despacho.\nO chefe está no gabinete dele." },
  { es: "embarazoso", pt: "constrangedor", ex: "Fue una situación embarazosa.\nFoi uma situação constrangedora." },
  { es: "zurdo / zurda", pt: "canhoto / canhota", ex: "Mi hijo es zurdo.\nMeu filho é canhoto." },
  { es: "la ganancia", pt: "lucro", ex: "La empresa tuvo buenas ganancias.\nA empresa teve bons lucros.", note: "ganância = la codicia" },
  { es: "la billetera", pt: "carteira (de dinheiro)", ex: "Perdí mi billetera.\nPerdi minha carteira.", note: "Espanha: la cartera" },
  { es: "el boleto", pt: "passagem / bilhete", ex: "Compré el boleto de avión.\nComprei a passagem de avião.", note: "boleto bancário = la factura" },
  { es: "el peaje", pt: "pedágio", ex: "Pagamos tres peajes en el viaje.\nPagamos três pedágios na viagem." },
  { es: "el timbre", pt: "campainha", ex: "Alguien toca el timbre.\nAlguém está tocando a campainha." },
  { es: "acostarse", pt: "deitar-se", ex: "Me acuesto a las once.\nDeito às onze.", note: "encostar = apoyar" },
  { es: "la asignatura", pt: "matéria (escolar)", ex: "Mi asignatura favorita es historia.\nMinha matéria favorita é história.", note: "assinatura = la firma" },
  { es: "jubilarse", pt: "aposentar-se", ex: "Mi padre se jubila este año.\nMeu pai se aposenta este ano." },
  { es: "la jubilación", pt: "aposentadoria", ex: "Ahorra para la jubilación.\nEle poupa para a aposentadoria." },
  { es: "el cachorro", pt: "filhote", ex: "La perra tuvo cinco cachorros.\nA cadela teve cinco filhotes.", note: "cachorro (PT) = el perro" },
  { es: "el perro", pt: "cachorro / cão", ex: "El perro ladra mucho.\nO cachorro late muito." },
  { es: "despedir", pt: "demitir", ex: "La empresa despidió a diez empleados.\nA empresa demitiu dez funcionários.", note: "despedir-se = despedirse" },
  { es: "cobrar", pt: "receber (pagamento)", ex: "Cobro a fin de mes.\nRecebo no fim do mês." },
  { es: "prestar", pt: "emprestar", ex: "¿Me prestas tu coche?\nMe empresta seu carro?" },
  { es: "pedir prestado", pt: "pegar emprestado", ex: "Pedí prestado un libro.\nPeguei um livro emprestado." },
  { es: "regalar", pt: "dar de presente", ex: "Me regalaron una bici.\nMe deram uma bicicleta de presente.", note: "el regalo = o presente" },
  { es: "regatear", pt: "pechinchar", ex: "En el mercado se puede regatear.\nNo mercado dá para pechinchar." },
  { es: "botar", pt: "jogar fora (LatAm)", ex: "Bota esa caja vieja.\nJoga fora essa caixa velha.", note: "botar (PT: pôr) = poner" },
  { es: "meter", pt: "colocar dentro", ex: "Mete la ropa en la maleta.\nColoca a roupa na mala." },
  { es: "elegir", pt: "escolher", ex: "Elige un número.\nEscolhe um número.", note: "também: escoger" },
  { es: "recoger", pt: "recolher / buscar (alguém)", ex: "Recojo a los niños a las cinco.\nBusco as crianças às cinco." },
  { es: "soler", pt: "costumar", ex: "Suelo caminar por la mañana.\nCostumo caminhar de manhã." },
  { es: "firmar", pt: "assinar", ex: "Firma aquí, por favor.\nAssina aqui, por favor." },
  { es: "rellenar", pt: "preencher", ex: "Rellena el formulario.\nPreenche o formulário." },
  { es: "enterarse", pt: "ficar sabendo", ex: "Me enteré de la noticia hoy.\nFiquei sabendo da notícia hoje." },
  { es: "averiguar", pt: "descobrir / verificar", ex: "Voy a averiguar el horario.\nVou verificar o horário." },
  { es: "suceder", pt: "acontecer", ex: "¿Qué sucedió aquí?\nO que aconteceu aqui?" },
  { es: "darse cuenta", pt: "perceber", ex: "No me di cuenta del error.\nNão percebi o erro.", note: "não é 'dar-se conta' apenas — uso muito mais comum" },
  { es: "meter la pata", pt: "dar mancada", ex: "Metí la pata en la reunión.\nDei uma mancada na reunião." },
  { es: "tomar el pelo", pt: "zoar / enganar", ex: "¿Me estás tomando el pelo?\nVocê está me zoando?" },
  { es: "estar harto", pt: "estar de saco cheio", ex: "Estoy harto del tráfico.\nEstou de saco cheio do trânsito." },
  { es: "por si acaso", pt: "por via das dúvidas", ex: "Lleva paraguas, por si acaso.\nLeva guarda-chuva, por via das dúvidas." },
  { es: "menos mal", pt: "ainda bem", ex: "Menos mal que llegaste.\nAinda bem que você chegou." },
  { es: "¡qué lástima!", pt: "que pena!", ex: "¡Qué lástima que no vengas!\nQue pena que você não vem!", note: "'qué pena' em alguns países = que vergonha" },
  { es: "madrugar", pt: "acordar cedo", ex: "Mañana tengo que madrugar.\nAmanhã tenho que acordar cedo." },
  { es: "trasnochar", pt: "virar a noite", ex: "Trasnoché estudiando.\nVirei a noite estudando." },
  { es: "adelgazar", pt: "emagrecer", ex: "Quiero adelgazar tres kilos.\nQuero emagrecer três quilos." },
  { es: "lastimarse", pt: "machucar-se", ex: "Se lastimó jugando.\nSe machucou jogando." },
  { es: "resbalar", pt: "escorregar", ex: "Resbalé en el piso mojado.\nEscorreguei no chão molhado." },
  { es: "trepar", pt: "escalar / subir", ex: "El gato trepó al árbol.\nO gato subiu na árvore." },
  { es: "arrojar", pt: "atirar / jogar", ex: "Arrojó la pelota lejos.\nJogou a bola longe." },
  { es: "el ascensor", pt: "elevador", ex: "El ascensor no funciona.\nO elevador está quebrado.", note: "LatAm: el elevador" },
  { es: "el pasillo", pt: "corredor", ex: "El baño está al final del pasillo.\nO banheiro fica no fim do corredor." },
  { es: "el techo", pt: "teto", ex: "Hay una mancha en el techo.\nTem uma mancha no teto.", note: "telhado = el tejado" },
  { es: "la cerradura", pt: "fechadura", ex: "La llave no entra en la cerradura.\nA chave não entra na fechadura." },
  { es: "el cajero automático", pt: "caixa eletrônico", ex: "¿Hay un cajero cerca?\nTem um caixa eletrônico perto?" },
  { es: "la nevera", pt: "geladeira", ex: "La leche está en la nevera.\nO leite está na geladeira.", note: "LatAm: el refrigerador / la heladera" },
  { es: "la estufa", pt: "fogão (Méx.) / aquecedor (Esp.)", ex: "La sopa está en la estufa.\nA sopa está no fogão.", note: "Espanha: fogão = la cocina" },
  { es: "el horno", pt: "forno", ex: "El pan está en el horno.\nO pão está no forno." },
  { es: "la licuadora", pt: "liquidificador", ex: "Haz el jugo en la licuadora.\nFaz o suco no liquidificador." },
  { es: "la plancha", pt: "ferro de passar", ex: "La plancha está caliente.\nO ferro está quente." },
  { es: "planchar", pt: "passar roupa", ex: "Odio planchar camisas.\nOdeio passar camisas." },
  { es: "el lavabo", pt: "pia (do banheiro)", ex: "Lava las manos en el lavabo.\nLava as mãos na pia." },
  { es: "el fregadero", pt: "pia (da cozinha)", ex: "Los platos están en el fregadero.\nOs pratos estão na pia." },
  { es: "el inodoro", pt: "vaso sanitário", ex: "El inodoro está tapado.\nO vaso sanitário está entupido." },
  { es: "el foco", pt: "lâmpada (LatAm)", ex: "Hay que cambiar el foco.\nTem que trocar a lâmpada.", note: "Espanha: la bombilla" },
  { es: "el florero", pt: "vaso (de flores)", ex: "Puse las rosas en el florero.\nColoquei as rosas no vaso." },
  { es: "la maceta", pt: "vaso (de planta)", ex: "La planta necesita una maceta más grande.\nA planta precisa de um vaso maior." },
  { es: "el césped", pt: "grama", ex: "No pises el césped.\nNão pise na grama." },
  { es: "la falda", pt: "saia", ex: "Ella lleva una falda azul.\nEla está de saia azul." },
  { es: "los calcetines", pt: "meias", ex: "Compré calcetines de lana.\nComprei meias de lã.", note: "LatAm: las medias" },
  { es: "la bufanda", pt: "cachecol", ex: "Ponte la bufanda, hace frío.\nPõe o cachecol, está frio." },
  { es: "los guantes", pt: "luvas", ex: "Olvidé mis guantes.\nEsqueci minhas luvas." },
  { es: "el abrigo", pt: "casaco", ex: "Necesitas un abrigo en invierno.\nVocê precisa de um casaco no inverno." },
  { es: "la corbata", pt: "gravata", ex: "Lleva corbata al trabajo.\nEle usa gravata no trabalho." },
  { es: "las gafas", pt: "óculos", ex: "No encuentro mis gafas.\nNão acho meus óculos.", note: "LatAm: los lentes / los anteojos" },
  { es: "el paraguas", pt: "guarda-chuva", ex: "Va a llover, lleva el paraguas.\nVai chover, leva o guarda-chuva." },
  { es: "el pañuelo", pt: "lenço", ex: "¿Tienes un pañuelo?\nVocê tem um lenço?" },
  { es: "el traje", pt: "terno", ex: "Compró un traje para la boda.\nComprou um terno para o casamento." },
  { es: "los vaqueros", pt: "calça jeans", ex: "Los vaqueros son cómodos.\nO jeans é confortável.", note: "LatAm: los jeans" },
  { es: "las zapatillas", pt: "tênis (calçado)", ex: "Corro con zapatillas nuevas.\nCorro com tênis novo.", note: "LatAm: los tenis" },
  { es: "la talla", pt: "tamanho (de roupa)", ex: "¿Qué talla usas?\nQue tamanho você usa?" },
  { es: "el probador", pt: "provador", ex: "¿Dónde está el probador?\nOnde fica o provador?" },
  { es: "la rebaja", pt: "desconto / liquidação", ex: "Hay rebajas en enero.\nTem liquidação em janeiro." },
  { es: "la ganga", pt: "pechincha", ex: "¡Este precio es una ganga!\nEste preço é uma pechincha!" },
  { es: "la boda", pt: "casamento (cerimônia)", ex: "La boda es en junio.\nO casamento é em junho." },
  { es: "la niebla", pt: "neblina", ex: "Hay mucha niebla en la carretera.\nTem muita neblina na estrada." },
  { es: "la tormenta", pt: "tempestade", ex: "Viene una tormenta.\nVem uma tempestade." },
  { es: "la ola", pt: "onda", ex: "Las olas están altas hoy.\nAs ondas estão altas hoje." },
  { es: "la orilla", pt: "beira / margem", ex: "Caminamos por la orilla del río.\nCaminhamos pela margem do rio." },
  { es: "el sobre", pt: "envelope", ex: "Mete la carta en el sobre.\nColoca a carta no envelope.", note: "sobre (preposição) também existe" },
  { es: "el ladrillo", pt: "tijolo", ex: "La casa es de ladrillo.\nA casa é de tijolo." },
  { es: "el letrero", pt: "placa / letreiro", ex: "El letrero dice 'cerrado'.\nA placa diz 'fechado'." },
  { es: "el ropero", pt: "guarda-roupa", ex: "Guarda la ropa en el ropero.\nGuarda a roupa no guarda-roupa.", note: "também: el armario" },
  { es: "la percha", pt: "cabide", ex: "Cuelga la camisa en la percha.\nPendura a camisa no cabide.", note: "LatAm: el gancho" },
  { es: "el cepillo", pt: "escova", ex: "¿Dónde está mi cepillo de dientes?\nOnde está minha escova de dentes?" },
  { es: "el peine", pt: "pente", ex: "Necesito un peine.\nPreciso de um pente." },
  { es: "el jabón", pt: "sabonete / sabão", ex: "No hay jabón en el baño.\nNão tem sabonete no banheiro." },
  { es: "el hilo", pt: "fio / linha", ex: "Compra hilo dental.\nCompra fio dental." },
  { es: "la aguja", pt: "agulha", ex: "No encuentro la aguja.\nNão acho a agulha." },
  { es: "el martillo", pt: "martelo", ex: "Necesito un martillo y clavos.\nPreciso de um martelo e pregos.", note: "el clavo = o prego" },
  { es: "el oso", pt: "urso", ex: "El oso duerme en invierno.\nO urso dorme no inverno." },
  { es: "el ratón", pt: "camundongo / mouse", ex: "El gato persigue al ratón.\nO gato persegue o camundongo.", note: "rato grande = la rata" },
  { es: "el tiburón", pt: "tubarão", ex: "Vimos un tiburón en el acuario.\nVimos um tubarão no aquário." },
  { es: "la ardilla", pt: "esquilo", ex: "La ardilla come nueces.\nO esquilo come nozes." },
  { es: "el mono", pt: "macaco", ex: "El mono salta entre los árboles.\nO macaco pula entre as árvores.", note: "¡qué mono! = que fofo!" },
  { es: "la mariposa", pt: "borboleta", ex: "La mariposa es azul.\nA borboleta é azul." },
  { es: "la hormiga", pt: "formiga", ex: "Hay hormigas en la cocina.\nTem formigas na cozinha." },
  { es: "el zorro", pt: "raposa", ex: "El zorro es muy astuto.\nA raposa é muito astuta." },
  { es: "el murciélago", pt: "morcego", ex: "El murciélago sale de noche.\nO morcego sai à noite." },
  { es: "el búho", pt: "coruja", ex: "El búho duerme de día.\nA coruja dorme de dia." },
  { es: "la rana", pt: "rã / sapo", ex: "La rana salta al agua.\nA rã pula na água." },
  { es: "el cerdo", pt: "porco", ex: "El cerdo vive en la granja.\nO porco vive na fazenda.", note: "LatAm: el chancho / el puerco" },
  { es: "la ternera", pt: "vitela / carne bovina", ex: "Un filete de ternera, por favor.\nUm filé de vitela, por favor.", note: "LatAm: la carne de res" },
  { es: "el pulpo", pt: "polvo (animal)", ex: "El pulpo tiene ocho brazos.\nO polvo tem oito braços.", note: "pó / poeira = el polvo" },
  { es: "el plátano", pt: "banana", ex: "Como un plátano al día.\nComo uma banana por dia.", note: "LatAm: el banano / la banana" },
  { es: "la naranja", pt: "laranja", ex: "El jugo de naranja está fresco.\nO suco de laranja está fresco." },
  { es: "el maní", pt: "amendoim", ex: "Compré maní tostado.\nComprei amendoim torrado.", note: "Espanha: el cacahuete; Méx.: el cacahuate" },
  { es: "la nuez", pt: "noz", ex: "El pastel lleva nueces.\nO bolo leva nozes." },
  { es: "la mantequilla", pt: "manteiga", ex: "Pan con mantequilla.\nPão com manteiga." },
  { es: "la mermelada", pt: "geleia", ex: "Mermelada de fresa.\nGeleia de morango." },
  { es: "la pimienta", pt: "pimenta-do-reino", ex: "Sal y pimienta, por favor.\nSal e pimenta, por favor.", note: "pimenta ardida = el ají / el chile" },
  { es: "el ají", pt: "pimenta (LatAm)", ex: "Esta salsa lleva ají.\nEste molho leva pimenta.", note: "México: el chile; Espanha: la guindilla" },
  { es: "la calabaza", pt: "abóbora", ex: "Sopa de calabaza.\nSopa de abóbora." },
  { es: "el champiñón", pt: "cogumelo", ex: "Pizza de champiñones.\nPizza de cogumelos.", note: "também: la seta / el hongo" },
  { es: "la harina", pt: "farinha", ex: "El pan se hace con harina.\nO pão é feito com farinha." },
  { es: "el maíz", pt: "milho", ex: "Tortillas de maíz.\nTortilhas de milho.", note: "milho verde (Am. do Sul): el choclo" },
  { es: "el perejil", pt: "salsinha", ex: "Pica el perejil.\nPica a salsinha.", note: "molho = la salsa" },
  { es: "la chuleta", pt: "costeleta / bisteca", ex: "Chuletas de cerdo a la parrilla.\nBistecas de porco na grelha." },
  { es: "el bocadillo", pt: "sanduíche (Espanha)", ex: "Un bocadillo de jamón.\nUm sanduíche de presunto.", note: "LatAm: el sándwich" },
  { es: "la torta", pt: "bolo (LatAm) / sanduíche (Méx.)", ex: "La torta de cumpleaños.\nO bolo de aniversário.", note: "o sentido muda por país!" },
  { es: "el caramelo", pt: "bala / doce", ex: "El niño quiere un caramelo.\nO menino quer uma bala.", note: "LatAm também: el dulce" },
  { es: "la carnicería", pt: "açougue", ex: "Compro carne en la carnicería.\nCompro carne no açougue." },
  { es: "rojo", pt: "vermelho", ex: "El semáforo está en rojo.\nO sinal está vermelho." },
  { es: "negro", pt: "preto", ex: "Un café negro, por favor.\nUm café preto, por favor." },
  { es: "gris", pt: "cinza", ex: "El cielo está gris.\nO céu está cinza." },
  { es: "morado", pt: "roxo", ex: "Le quedó un moretón morado.\nFicou um roxo (hematoma) nele." },
  { es: "rubio / rubia", pt: "loiro / loira", ex: "Mi hermana es rubia.\nMinha irmã é loira." },
  { es: "pelirrojo / pelirroja", pt: "ruivo / ruiva", ex: "El actor es pelirrojo.\nO ator é ruivo." },
  { es: "calvo", pt: "careca", ex: "Mi tío es calvo.\nMeu tio é careca." },
  { es: "lunes", pt: "segunda-feira", ex: "El lunes empiezo el curso.\nNa segunda começo o curso.", note: "os dias úteis não são 'feiras' em espanhol" },
  { es: "martes", pt: "terça-feira", ex: "El martes tengo médico.\nNa terça tenho médico.", note: "martes 13 = a 'sexta-feira 13' deles" },
  { es: "miércoles", pt: "quarta-feira", ex: "La reunión es el miércoles.\nA reunião é na quarta." },
  { es: "jueves", pt: "quinta-feira", ex: "El jueves hay partido.\nNa quinta tem jogo." },
  { es: "viernes", pt: "sexta-feira", ex: "¡Por fin es viernes!\nAté que enfim é sexta!" },
  { es: "enero", pt: "janeiro", ex: "En enero hace calor en Brasil.\nEm janeiro faz calor no Brasil." },
  { es: "el sacapuntas", pt: "apontador", ex: "¿Tienes un sacapuntas?\nVocê tem um apontador?" },
  { es: "las vacaciones", pt: "férias", ex: "Estoy de vacaciones.\nEstou de férias." },
  { es: "el cumpleaños", pt: "aniversário", ex: "¡Feliz cumpleaños!\nFeliz aniversário!" },
  { es: "la Navidad", pt: "Natal", ex: "La Navidad es en diciembre.\nO Natal é em dezembro." },
  { es: "el juguete", pt: "brinquedo", ex: "El niño quiere un juguete.\nO menino quer um brinquedo." },
  { es: "flaco / flaca", pt: "magro / magra", ex: "El gato está muy flaco.\nO gato está muito magro.", note: "Espanha prefere: delgado" },
  { es: "delgado / delgada", pt: "magro / esbelto", ex: "Es alta y delgada.\nEla é alta e magra." },
  { es: "guapo / guapa", pt: "bonito / bonita", ex: "Tu novio es muy guapo.\nSeu namorado é muito bonito." },
  { es: "listo / lista", pt: "esperto / pronto", ex: "¿Estás listo?\nVocê está pronto?", note: "ser listo = ser esperto; estar listo = estar pronto" },
  { es: "tonto / tonta", pt: "bobo / boba", ex: "No seas tonto.\nNão seja bobo." },
  { es: "terco / terca", pt: "teimoso / teimosa", ex: "Es terco como una mula.\nÉ teimoso como uma mula." },
  { es: "tacaño / tacaña", pt: "pão-duro", ex: "Es rico pero tacaño.\nÉ rico mas pão-duro." },
  { es: "perezoso / perezosa", pt: "preguiçoso / preguiçosa", ex: "El domingo me pongo perezoso.\nNo domingo fico preguiçoso.", note: "LatAm também: flojo" },
  { es: "aburrido / aburrida", pt: "entediado / chato", ex: "La película es aburrida.\nO filme é chato." },
  { es: "enojado / enojada", pt: "bravo / com raiva", ex: "Está enojada conmigo.\nEla está brava comigo.", note: "Espanha: enfadado" },
  { es: "sencillo / sencilla", pt: "simples", ex: "Es una receta sencilla.\nÉ uma receita simples." },
  { es: "lleno / llena", pt: "cheio / cheia", ex: "El restaurante está lleno.\nO restaurante está cheio." },
  { es: "roto / rota", pt: "quebrado / quebrada", ex: "El vaso está roto.\nO copo está quebrado." },
  { es: "mayor", pt: "mais velho / idoso", ex: "Mi hermano mayor vive en Lima.\nMeu irmão mais velho mora em Lima." },
  { es: "apagar", pt: "desligar / apagar", ex: "Apaga la tele.\nDesliga a TV." },
  { es: "prender", pt: "ligar / acender (LatAm)", ex: "Prende la luz.\nLiga a luz.", note: "prender (PT: deter) = detener" },
  { es: "ponerse", pt: "vestir / ficar (+ adjetivo)", ex: "Se puso triste.\nEle ficou triste." },
  { es: "pararse", pt: "levantar-se (LatAm)", ex: "El público se paró a aplaudir.\nO público se levantou para aplaudir.", note: "Espanha: só 'parar'" },
  { es: "renunciar", pt: "pedir demissão", ex: "Renunció a su trabajo.\nPediu demissão do trabalho." },
  { es: "apuntar", pt: "anotar", ex: "Apunta mi número.\nAnota meu número.", note: "também: apontar (mirar)" },
  { es: "sanar", pt: "sarar / curar", ex: "La herida ya sanó.\nA ferida já sarou." },
  { es: "enfermarse", pt: "ficar doente", ex: "Me enfermé en el viaje.\nFiquei doente na viagem." },
  { es: "platicar", pt: "conversar (Méx.)", ex: "Platicamos un rato.\nConversamos um pouco." },
  { es: "la plata", pt: "dinheiro (LatAm) / prata", ex: "No tengo plata.\nNão tenho dinheiro." },
  { es: "la lana", pt: "lã", ex: "El suéter es de lana.\nO suéter é de lã.", note: "México (gíria): dinheiro" },
  { es: "el sueldo", pt: "salário", ex: "El sueldo llega el día cinco.\nO salário cai no dia cinco." },
  { es: "el logro", pt: "conquista", ex: "Fue un gran logro.\nFoi uma grande conquista." },
  { es: "el reto", pt: "desafio", ex: "Es un reto difícil.\nÉ um desafio difícil." },
  { es: "la broma", pt: "brincadeira", ex: "Es solo una broma.\nÉ só uma brincadeira." },
  { es: "el chiste", pt: "piada", ex: "Cuenta un chiste.\nConta uma piada." },
  { es: "las cosquillas", pt: "cócegas", ex: "¡No me hagas cosquillas!\nNão me faz cócegas!" },
  { es: "el apodo", pt: "apelido", ex: "Su apodo es 'Flaco'.\nO apelido dele é 'Magrão'.", note: "sobrenome = el apellido" },
  { es: "la niñera", pt: "babá", ex: "La niñera cuida al bebé.\nA babá cuida do bebê." },
  { es: "el jubilado / la jubilada", pt: "aposentado / aposentada", ex: "Mi abuelo está jubilado.\nMeu avô é aposentado." },
  { es: "la encuesta", pt: "pesquisa / enquete", ex: "Respondí una encuesta.\nRespondi uma pesquisa." },
  { es: "el informe", pt: "relatório", ex: "Entrego el informe mañana.\nEntrego o relatório amanhã." },
  { es: "la contraseña", pt: "senha", ex: "Olvidé mi contraseña.\nEsqueci minha senha." },
  { es: "el correo", pt: "e-mail / correio", ex: "Te mando un correo.\nTe mando um e-mail." },
  { es: "el enlace", pt: "link", ex: "Haz clic en el enlace.\nClica no link." },
  { es: "la pantalla", pt: "tela", ex: "La pantalla está sucia.\nA tela está suja." },
  { es: "descargar", pt: "baixar (arquivo)", ex: "Descarga la aplicación.\nBaixa o aplicativo." },
  { es: "ponerse de acuerdo", pt: "entrar em acordo", ex: "No nos ponemos de acuerdo.\nNão entramos em acordo." },
  { es: "a la vez", pt: "ao mesmo tempo", ex: "No hables y comas a la vez.\nNão fale e coma ao mesmo tempo." },
  { es: "tener éxito", pt: "fazer sucesso", ex: "La banda tuvo éxito.\nA banda fez sucesso." },
  { es: "hacer caso", pt: "obedecer / dar atenção", ex: "El niño no hace caso.\nO menino não obedece." },
  { es: "dormir la siesta", pt: "tirar uma soneca", ex: "Duermo la siesta después del almuerzo.\nTiro uma soneca depois do almoço." },
  { es: "ni modo", pt: "fazer o quê (Méx.)", ex: "Ni modo, ya pasó.\nFazer o quê, já passou." },
  { es: "¡aguas!", pt: "cuidado! (Méx.)", ex: "¡Aguas con el perro!\nCuidado com o cachorro!" },
  { es: "buena onda", pt: "gente boa / legal", ex: "Tu amigo es buena onda.\nSeu amigo é gente boa." },
  { es: "el desarrollo", pt: "desenvolvimento", ex: "El desarrollo del proyecto va bien.\nO desenvolvimento do projeto vai bem." },
];
